import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const links = [
		{ href: "/", label: "Home" },
		{ href: "/docs", label: "Docs" },
		{ href: "/todos", label: "App" },
	];
	return (
		<html lang='en' suppressHydrationWarning={true}>
			<body className={inter.className} suppressHydrationWarning={true}>
				<div className='container mx-auto'>
					<header>
						<nav className='text-center'>
							<ul className='flex items-center space-x-3 bg-white p-5'>
								{links.map((link) => (
									<li key={link.href}>
										<Link href={link.href} className='text-black'>
											{link.label}
										</Link>
									</li>
								))}
							</ul>
						</nav>
					</header>
					{children}
				</div>
			</body>
		</html>
	);
}
